### ISSUE TITLE
rsparcc默认安不上

### ISSUE THREAD

**Issue by lihaicheng7003** [xiaolw95/NetMoss2#1]
rsparcc 在 cran 好像安不上， 去 github 安装的。
我的安包过程
```r
library(devtools)

install_github("MPBA/r-sparcc")

install.packages("WGCNA")

BiocManager::install("impute")

BiocManager::install("preprocessCore")

install_github("xiaolw95/NetMoss2")
# 终于安装成功
```

**Comment by xiaolw95** [comment]
抱歉，我后来也发现了这个问题。我会把这个提示写进README的。

**Comment by ZhangMin-123** [comment]
你好，我按楼主的代码安装netMass2,报错内容如下：
Error: package or namespace load failed for 'WGCNA' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called 'GO.db'
请问如何解决呢？

**Comment by ZhangMin-123** [comment]
你好，我按楼主的代码安装netMass2, 报错内容如下：
Error: package or namespace load failed for 'WGCNA' in loadNamespace(i, c(lib.loc, .libPaths()), versionCheck = vI[[i]]):
 there is no package called 'GO.db'
请问如何解决呢？
